# Generated by Django 3.1.2 on 2020-10-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '友情链接python manage.py createsuperuser', 'verbose_name_plural': '友情链接python manage.py createsuperuser'},
        ),
    ]
