# Generated by Django 3.1.2 on 2020-11-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20201030_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.recommended', verbose_name='推荐位'),
        ),
    ]
